site:
  title: Dialogue Branch Documentation Hub
  url: https://www.dialoguebranch.com/docs/
  start_page: dialogue-branch::index.adoc
content:
  sources:
  - url: ./
    branches: HEAD
    start_path: docs
ui:
  bundle:
    url: ./dlb-ui-bundle-latest.zip
